application.version=@project.version@
application.projectName=@project.artifactId@
logging.level.root=INFO
logging.file.name=logs/ExcelUtils.log
counterarguments.analyzetrx=2
counterarguments.fusiontrx=2
counterarguments.formatactivity=2
counterarguments.directoryparser=2
counterarguments.lissage=4
analyzetrx.sheetIn=sheet1
analyzetrx.sheetOut=Datas
analyzetrx.pathModel=model/model Analyze TRX.xlsm
analyzetrx.pathResultFile=Analyze TRX-aaaa-mm-jj.xlsm
correctionimputation.action=false
formatinvregisterln.lastcolumn=59
formatinvregisterln.nohidecolumns=4,34,35,36,49,52,58
formatactivity.hiddencolumns=0,1,2,3,4,5,8,9,12,15,16,17,20,21,22,23,24,25,26
